import { z } from "zod";

// Prisma enums as Zod schemas for validation
export const RoleSchema = z.enum(["BATSMAN", "BOWLER", "ALL_ROUNDER"]);
export const BattingHandSchema = z.enum(["RIGHT", "LEFT"]);
export const BowlingStyleSchema = z.enum(["FAST", "MEDIUM_FAST", "SPIN"]);
export const InvitationStatusSchema = z.enum(["PENDING", "ACCEPTED", "REJECTED"]);

// Create insert schemas for validation
export const insertUserSchema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
  username: z.string().optional(),
  role: RoleSchema.optional(),
  battingHand: BattingHandSchema.optional(),
  bowlingStyle: BowlingStyleSchema.optional(),
  profileComplete: z.boolean().optional(),
});

export const insertCareerStatsSchema = z.object({
  userId: z.string(),
  matchesPlayed: z.number().int().min(0).optional(),
  totalRuns: z.number().int().min(0).optional(),
  ballsFaced: z.number().int().min(0).optional(),
  strikeRate: z.number().min(0).optional(),
  oversBowled: z.number().min(0).optional(),
  runsConceded: z.number().int().min(0).optional(),
  wicketsTaken: z.number().int().min(0).optional(),
  economy: z.number().min(0).optional(),
  catchesTaken: z.number().int().min(0).optional(),
});

export const insertTeamSchema = z.object({
  name: z.string().min(1),
  description: z.string().optional(),
  captainId: z.string(),
  viceCaptainId: z.string().optional(),
});

export const insertTeamMemberSchema = z.object({
  teamId: z.string(),
  userId: z.string(),
});

export const insertTeamInvitationSchema = z.object({
  teamId: z.string(),
  invitedBy: z.string(),
  invitedUser: z.string(),
  status: InvitationStatusSchema.optional(),
});

export const insertMatchSchema = z.object({
  userId: z.string(),
  opponent: z.string().min(1),
  matchDate: z.date(),
  runsScored: z.number().int().min(0),
  ballsFaced: z.number().int().min(0),
  oversBowled: z.number().min(0),
  runsConceded: z.number().int().min(0),
  wicketsTaken: z.number().int().min(0),
  catchesTaken: z.number().int().min(0),
});

// Frontend form schema for match input
export const matchFormSchema = insertMatchSchema.omit({ userId: true }).extend({
  matchDate: z.string(),
});

// Profile setup schema
export const profileSetupSchema = z.object({
  username: z.string().min(3).max(30),
  role: z.enum(["BATSMAN", "BOWLER", "ALL_ROUNDER"]),
  battingHand: z.enum(["RIGHT", "LEFT"]),
  bowlingStyle: z.enum(["FAST", "MEDIUM_FAST", "SPIN"]).optional(),
});

// Auth schemas
export const loginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
});

export const registerSchema = z.object({
  email: z.string().email(),
  password: z.string().min(6),
});

// Types - these will be generated by Prisma, but we define them for TypeScript compatibility
export type Role = z.infer<typeof RoleSchema>;
export type BattingHand = z.infer<typeof BattingHandSchema>;
export type BowlingStyle = z.infer<typeof BowlingStyleSchema>;
export type InvitationStatus = z.infer<typeof InvitationStatusSchema>;

export type InsertUser = z.infer<typeof insertUserSchema>;
export type InsertCareerStats = z.infer<typeof insertCareerStatsSchema>;
export type InsertTeam = z.infer<typeof insertTeamSchema>;
export type InsertTeamMember = z.infer<typeof insertTeamMemberSchema>;
export type InsertTeamInvitation = z.infer<typeof insertTeamInvitationSchema>;
export type InsertMatch = z.infer<typeof insertMatchSchema>;
export type ProfileSetup = z.infer<typeof profileSetupSchema>;
export type LoginRequest = z.infer<typeof loginSchema>;
export type RegisterRequest = z.infer<typeof registerSchema>;

// Re-export Prisma model types
export type { User, CareerStats, Team, TeamMember, TeamInvitation, Match } from "@prisma/client";